/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel; // Import JPanel for creating panels

/**
 * L01 - Create a Java console program to manage Candidates of company
 * 
 * @author Nguyen Ho Phuoc An - CE190747
 */
/**
 * MenuFrame is the main menu interface for the application.
 */
public class MenuFrame extends javax.swing.JFrame {

    private final JPanel experiencePanel = new ExperiencePanel(); // Panel for experience candidates
    private final JPanel fresherPanel = new FresherPanel(); // Panel for fresher candidates
    private final JPanel internshipPanel = new InternshipPanel(); // Panel for internship candidates

    private boolean isExperienceSelected = false; // Flag to check if experience panel is selected
    private boolean isFresherSelected = false; // Flag to check if fresher panel is selected
    private boolean isInternshipSelected = false; // Flag to check if internship panel is selected

    /**
     * Creates new form MenuFrame.
     */
    public MenuFrame() {
        initComponents(); // Initialize components
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuExperience = new javax.swing.JMenu();
        menuFresher = new javax.swing.JMenu();
        menuInternship = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        menuExperience.setText("Experience");
        menuExperience.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuExperienceMousePressed(evt);
            }
        });
        jMenuBar1.add(menuExperience);

        menuFresher.setText("Fresher");
        menuFresher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuFresherMousePressed(evt);
            }
        });
        jMenuBar1.add(menuFresher);

        menuInternship.setText("Internship");
        menuInternship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuInternshipMousePressed(evt);
            }
        });
        jMenuBar1.add(menuInternship);

        menuClose.setText("Close");
        menuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCloseMousePressed(evt);
            }
        });
        jMenuBar1.add(menuClose);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1018, 590);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles mouse press events for the fresher menu option.
     * Closes any open menus and displays the fresher panel.
     */
    private void menuFresherMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuFresherMousePressed
        // Close any open menus
        menuCloseMousePressed(evt);
        // Set fresher selection state to true
        isFresherSelected = true;
        // Add fresher panel to the frame
        this.add(fresherPanel);
        // Resize the frame to fit the new panel
        this.pack();
    }// GEN-LAST:event_menuFresherMousePressed

    /**
     * Handles mouse press events for the experience menu option.
     * Closes any open menus and displays the experience panel.
     */
    private void menuExperienceMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuExperienceMousePressed
        // Close any open menus
        menuCloseMousePressed(evt);
        // Set experience selection state to true
        isExperienceSelected = true;
        // Add experience panel to the frame
        this.add(experiencePanel);
        // Resize the frame to fit the new panel
        this.pack();
    }// GEN-LAST:event_menuExperienceMousePressed

    /**
     * Handles mouse press events for closing the menu.
     * Removes any currently displayed panels and resets their selection states.
     */
    private void menuCloseMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuCloseMousePressed
        // Check if experience panel is selected
        if (isExperienceSelected) {
            // Remove experience panel from the frame
            this.remove(experiencePanel);
            // Reset experience selection state
            isExperienceSelected = false;
        }
        // Check if fresher panel is selected
        if (isFresherSelected) {
            // Remove fresher panel from the frame
            this.remove(fresherPanel);
            // Reset fresher selection state
            isFresherSelected = false;
        }
        // Check if internship panel is selected
        if (isInternshipSelected) {
            // Remove internship panel from the frame
            this.remove(internshipPanel);
            // Reset internship selection state
            isInternshipSelected = false;
        }
        // Set the size of the frame
        this.setSize(1018, 590);
    }// GEN-LAST:event_menuCloseMousePressed

    /**
     * Handles mouse press events for the internship menu option.
     * Closes any open menus and displays the internship panel.
     */
    private void menuInternshipMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuInternshipMousePressed
        // Close any open menus
        menuCloseMousePressed(evt);
        // Set internship selection state to true
        isInternshipSelected = true;
        // Add internship panel to the frame
        this.add(internshipPanel);
        // Resize the frame to fit the new panel
        this.pack();
    }// GEN-LAST:event_menuInternshipMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClose;
    private javax.swing.JMenu menuExperience;
    private javax.swing.JMenu menuFresher;
    private javax.swing.JMenu menuInternship;
    // End of variables declaration//GEN-END:variables
}
