/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author PeterNguyen
 */
public class MenuFrame extends javax.swing.JFrame {

    private final JPanel experiencePanel = new ExperiencePanel();
    private final JPanel fresherPanel = new FresherPanel();
    private final JPanel internshipPanel = new InternshipPanel();

    private boolean isExperienceSelected = false;
    private boolean isFresherSelected = false;
    private boolean isInternshipSelected = false;

    /**
     * Creates new form MenuView
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuExperience = new javax.swing.JMenu();
        menuFresher = new javax.swing.JMenu();
        menuInternship = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        menuExperience.setText("Experience");
        menuExperience.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuExperienceMousePressed(evt);
            }
        });
        jMenuBar1.add(menuExperience);

        menuFresher.setText("Fresher");
        menuFresher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuFresherMousePressed(evt);
            }
        });
        jMenuBar1.add(menuFresher);

        menuInternship.setText("Internship");
        menuInternship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuInternshipMousePressed(evt);
            }
        });
        jMenuBar1.add(menuInternship);

        menuClose.setText("Close");
        menuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCloseMousePressed(evt);
            }
        });
        jMenuBar1.add(menuClose);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1018, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFresherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFresherMousePressed
        menuCloseMousePressed(evt);
        isFresherSelected = true;
        this.add(fresherPanel);
        this.pack();
    }//GEN-LAST:event_menuFresherMousePressed

    private void menuExperienceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExperienceMousePressed
        menuCloseMousePressed(evt);
        isExperienceSelected = true;
        this.add(experiencePanel);
        this.pack();
    }//GEN-LAST:event_menuExperienceMousePressed

    private void menuCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCloseMousePressed
        if (isExperienceSelected) {
            this.remove(experiencePanel);
            isExperienceSelected = false;
        }
        if (isFresherSelected) {
            this.remove(fresherPanel);
            isFresherSelected = false;
        }
        if (isInternshipSelected) {
            this.remove(internshipPanel);
            isInternshipSelected = false;
        }
        this.setSize(1018, 590);
    }//GEN-LAST:event_menuCloseMousePressed

    private void menuInternshipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInternshipMousePressed
        menuCloseMousePressed(evt);
        isInternshipSelected = true;
        this.add(internshipPanel);
        this.pack();
    }//GEN-LAST:event_menuInternshipMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClose;
    private javax.swing.JMenu menuExperience;
    private javax.swing.JMenu menuFresher;
    private javax.swing.JMenu menuInternship;
    // End of variables declaration//GEN-END:variables
}
